[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:backend]
command=/hackflare-api
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
autorestart=true

[program:frontend]
command=./node_modules/.bin/react-router-serve ./build/server/index.js
directory=/app/frontend
environment=NODE_ENV="production"
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
autorestart=true
