services:
  api:
    profiles: [backend]
    build:
      context: .
      dockerfile: hackflare_api/Dockerfile
    env_file:
      - ../.env
    environment:
      - RUST_LOG=debug,hackflare=trace
    ports:
      - "8080:8080"
      - "53:5353/udp"
      - "53:5353/tcp"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    profiles: [backend]
    image: postgres:18
    shm_size: 256mb
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hackflare"]
      interval: 3s
      retries: 10
      start_period: 10s
    networks:
      - backend

  frontend:
    profiles: [frontend]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    networks:
      - backend

  pgadmin4:
    profiles: [backend]
    image: dpage/pgadmin4
    env_file:
      - ../.env
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
